"""Small Hamlet-only QA failure-analysis harness."""

from hamlet_qa.config import (
    DEFAULT_BM25_B,
    DEFAULT_BM25_K1,
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_CONTEXT_BUDGETS,
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_RANDOM_SEED,
    DEFAULT_READER_MODEL,
    DEFAULT_RERANKER_MODEL,
    DEFAULT_TEMPERATURE,
    DEFAULT_TREATMENTS,
    DEFAULT_TOKENIZER_MODEL,
    QUESTION_CATEGORIES,
    REASONING_SKILLS,
    RunConfig,
)

__all__ = [
    "DEFAULT_BM25_B",
    "DEFAULT_BM25_K1",
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_CONTEXT_BUDGETS",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_RANDOM_SEED",
    "DEFAULT_READER_MODEL",
    "DEFAULT_RERANKER_MODEL",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_TREATMENTS",
    "DEFAULT_TOKENIZER_MODEL",
    "QUESTION_CATEGORIES",
    "REASONING_SKILLS",
    "RunConfig",
]
