"""Small Hamlet-only QA failure-analysis harness."""

from hamlet_qa.config import (
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_CONTEXT_BUDGETS,
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_READER_MODEL,
    DEFAULT_TEMPERATURE,
    DEFAULT_TREATMENTS,
    QUESTION_CATEGORIES,
    RunConfig,
)

__all__ = [
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_CONTEXT_BUDGETS",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_READER_MODEL",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_TREATMENTS",
    "QUESTION_CATEGORIES",
    "RunConfig",
]
